spring.application.name=quartz-scheduler
server.port=8081

management.endpoints.web.exposure.include=prometheus,health,info,metrics
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true
management.metrics.tags.application=quartz-scheduler

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=scheduler-poc
kafka.topics.input=scheduled-jobs-input
kafka.topics.output=scheduled-jobs-output
kafka.topics.dlq=scheduled-jobs-dlq
kafka.batch.size=1000

logging.level.com.example=DEBUG
logging.level.org.quartz=INFO
logging.level.org.springframework.kafka=INFO